### ISSUE TITLE
Can't open roles page on dashboard

### ISSUE THREAD

**Issue by peter-wd-1** [authorizerdev/authorizer#183]
**Version:** x.y.z
0.26.0

**Describe the bug**
Hi, 
All worked fine on previous version but after I upgrade version > 0.26.0
When I open the dashboard/roles page I'm getting error below on browser console:
```
TypeError: Cannot read properties of undefined (reading 'length')
    at t1 (chunk-HMXZ6FVI.js:1:14340)
    at Fg (chunk-LXE7RGI3.js:5:52995)
    at z_ (chunk-LXE7RGI3.js:9:8745)
    at L_ (chunk-LXE7RGI3.js:9:950)
    at xF (chunk-LXE7RGI3.js:9:878)
    at Zu (chunk-LXE7RGI3.js:9:732)
    at s0 (chunk-LXE7RGI3.js:7:10899)
    at chunk-LXE7RGI3.js:5:38799
    at Re.unstable_runWithPriority (chunk-LXE7RGI3.js:1:12474)
    at Xa (chunk-LXE7RGI3.js:5:38577)
Kg @ chunk-LXE7RGI3.js:7

```

And can't see any component is loading

**Comment by lakhansamani** [comment]
Resolved in 0.27.0 https://github.com/authorizerdev/authorizer/commit/d8c662eaadaf308b172b582d681f50ba66a4b0f0
