### ISSUE TITLE
client_id

### ISSUE THREAD

**Issue by signaltech** [authorizerdev/authorizer#437]
**Version:** x.y.z

**Describe the bug**

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by signaltech** [comment]
both with IP and with domain pointing to the IP

**Comment by signaltech** [comment]
@lakhansamani any solution?

**Comment by lakhansamani** [comment]
While accessing the app in browser pls use domain that will help

**Comment by signaltech** [comment]
@lakhansamani Yeah I am using domain is there a HTTPS requirement(using domain but no SSL installed in the server so just HTTP)

**Comment by lakhansamani** [comment]
HTTP should be fine however do u see errors in network request. Somehow it is not allowed to set cookies and that is creating problems

**Comment by signaltech** [comment]
@lakhansamani  in the inspection console there is this error

Environment-Q72GB73P.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading '_env')
    at Environment-Q72GB73P.js:1:33481
    at Generator.next (<anonymous>)
    at a (chunk-I2F2WLKQ.js:1:1222)

**Comment by lakhansamani** [comment]
@signaltech can you try the latest version
Thanks

**Comment by signaltech** [comment]
@lakhansamani sorry I didn't respond. today I pulled the new changes and clean build but the error remains.
thank you

**Comment by signaltech** [comment]
upon testing on firefox here is the console output(not shown in chrome)

[users](http://auth.signaltech.xyz/dashboard/users)
Some cookies are misusing the recommended “SameSite“ attribute 2
Cookie “authorizer-admin” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [graphql](http://auth.signaltech.xyz/graphql)
Cookie “authorizer-admin” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [graphql](http://auth.signaltech.xyz/graphql)
Cookie “authorizer-admin” has been rejected because a non-HTTPS cookie can’t be set as “secure”. [graphql](http://auth.signaltech.xyz/graphql)
Cookie “authorizer-admin” has been rejected because a non-HTTPS cookie can’t be set as “secure”.

**Comment by signaltech** [comment]
install SSL certificate now it is working with HTTPS. thank you
